name: Test

on:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use python
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
